# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facerec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfacerec.proto\x12\x0f\x61veplen.facerec\";\n\x18\x45xtractFFVectorV1Request\x12\x12\n\nbucketname\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\")\n\x19\x45xtractFFVectorV1Response\x12\x0c\n\x04\x66\x66vc\x18\x01 \x03(\x01\x32\x7f\n\x0f\x46\x61\x63\x65Recognition\x12l\n\x11\x45xtractFFVectorV1\x12).aveplen.facerec.ExtractFFVectorV1Request\x1a*.aveplen.facerec.ExtractFFVectorV1Response\"\x00\x42\x32Z0github.com/aveplen-bach/face-recognition-serviceb\x06proto3')



_EXTRACTFFVECTORV1REQUEST = DESCRIPTOR.message_types_by_name['ExtractFFVectorV1Request']
_EXTRACTFFVECTORV1RESPONSE = DESCRIPTOR.message_types_by_name['ExtractFFVectorV1Response']
ExtractFFVectorV1Request = _reflection.GeneratedProtocolMessageType('ExtractFFVectorV1Request', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTFFVECTORV1REQUEST,
  '__module__' : 'facerec_pb2'
  # @@protoc_insertion_point(class_scope:aveplen.facerec.ExtractFFVectorV1Request)
  })
_sym_db.RegisterMessage(ExtractFFVectorV1Request)

ExtractFFVectorV1Response = _reflection.GeneratedProtocolMessageType('ExtractFFVectorV1Response', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTFFVECTORV1RESPONSE,
  '__module__' : 'facerec_pb2'
  # @@protoc_insertion_point(class_scope:aveplen.facerec.ExtractFFVectorV1Response)
  })
_sym_db.RegisterMessage(ExtractFFVectorV1Response)

_FACERECOGNITION = DESCRIPTOR.services_by_name['FaceRecognition']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/aveplen-bach/face-recognition-service'
  _EXTRACTFFVECTORV1REQUEST._serialized_start=34
  _EXTRACTFFVECTORV1REQUEST._serialized_end=93
  _EXTRACTFFVECTORV1RESPONSE._serialized_start=95
  _EXTRACTFFVECTORV1RESPONSE._serialized_end=136
  _FACERECOGNITION._serialized_start=138
  _FACERECOGNITION._serialized_end=265
# @@protoc_insertion_point(module_scope)
