// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: s3file.proto

package s3file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *ImageObject) Reset() {
	*x = ImageObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s3file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageObject) ProtoMessage() {}

func (x *ImageObject) ProtoReflect() protoreflect.Message {
	mi := &file_s3file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageObject.ProtoReflect.Descriptor instead.
func (*ImageObject) Descriptor() ([]byte, []int) {
	return file_s3file_proto_rawDescGZIP(), []int{0}
}

func (x *ImageObject) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageObject) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type GetImageObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetImageObjectRequest) Reset() {
	*x = GetImageObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s3file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageObjectRequest) ProtoMessage() {}

func (x *GetImageObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s3file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageObjectRequest.ProtoReflect.Descriptor instead.
func (*GetImageObjectRequest) Descriptor() ([]byte, []int) {
	return file_s3file_proto_rawDescGZIP(), []int{1}
}

func (x *GetImageObjectRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_s3file_proto protoreflect.FileDescriptor

var file_s3file_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x33, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x76, 0x65, 0x70, 0x6c, 0x65, 0x6e, 0x2e, 0x73, 0x33, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0b, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32,
	0xa8, 0x01, 0x0a, 0x09, 0x53, 0x33, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x45, 0x0a,
	0x0e, 0x50, 0x75, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x1b, 0x2e, 0x61, 0x76, 0x65, 0x70, 0x6c, 0x65, 0x6e, 0x2e, 0x73, 0x33, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x54, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x25, 0x2e, 0x61, 0x76, 0x65, 0x70, 0x6c, 0x65, 0x6e,
	0x2e, 0x73, 0x33, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x61, 0x76, 0x65, 0x70, 0x6c, 0x65, 0x6e, 0x2e, 0x73, 0x33, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x76, 0x65, 0x70, 0x6c, 0x65, 0x6e,
	0x2d, 0x62, 0x61, 0x63, 0x6b, 0x2f, 0x73, 0x33, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s3file_proto_rawDescOnce sync.Once
	file_s3file_proto_rawDescData = file_s3file_proto_rawDesc
)

func file_s3file_proto_rawDescGZIP() []byte {
	file_s3file_proto_rawDescOnce.Do(func() {
		file_s3file_proto_rawDescData = protoimpl.X.CompressGZIP(file_s3file_proto_rawDescData)
	})
	return file_s3file_proto_rawDescData
}

var file_s3file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_s3file_proto_goTypes = []interface{}{
	(*ImageObject)(nil),           // 0: aveplen.s3file.ImageObject
	(*GetImageObjectRequest)(nil), // 1: aveplen.s3file.GetImageObjectRequest
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_s3file_proto_depIdxs = []int32{
	0, // 0: aveplen.s3file.S3Gateway.PutImageObject:input_type -> aveplen.s3file.ImageObject
	1, // 1: aveplen.s3file.S3Gateway.GetImageObject:input_type -> aveplen.s3file.GetImageObjectRequest
	2, // 2: aveplen.s3file.S3Gateway.PutImageObject:output_type -> google.protobuf.Empty
	0, // 3: aveplen.s3file.S3Gateway.GetImageObject:output_type -> aveplen.s3file.ImageObject
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s3file_proto_init() }
func file_s3file_proto_init() {
	if File_s3file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s3file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s3file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s3file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s3file_proto_goTypes,
		DependencyIndexes: file_s3file_proto_depIdxs,
		MessageInfos:      file_s3file_proto_msgTypes,
	}.Build()
	File_s3file_proto = out.File
	file_s3file_proto_rawDesc = nil
	file_s3file_proto_goTypes = nil
	file_s3file_proto_depIdxs = nil
}
