# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x0e\x61veplen.config\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\rFacerecConfig\x12\x11\n\tthreshold\x18\x01 \x01(\x01\x32\xa5\x01\n\x06\x43onfig\x12K\n\x10GetFacerecConfig\x12\x16.google.protobuf.Empty\x1a\x1d.aveplen.config.FacerecConfig\"\x00\x12N\n\x13UpdateFacerecConfig\x12\x1d.aveplen.config.FacerecConfig\x1a\x16.google.protobuf.Empty\"\x00\x42 Z\x1egithub.com/aveplen-bach/configb\x06proto3')



_FACERECCONFIG = DESCRIPTOR.message_types_by_name['FacerecConfig']
FacerecConfig = _reflection.GeneratedProtocolMessageType('FacerecConfig', (_message.Message,), {
  'DESCRIPTOR' : _FACERECCONFIG,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:aveplen.config.FacerecConfig)
  })
_sym_db.RegisterMessage(FacerecConfig)

_CONFIG = DESCRIPTOR.services_by_name['Config']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\036github.com/aveplen-bach/config'
  _FACERECCONFIG._serialized_start=61
  _FACERECCONFIG._serialized_end=95
  _CONFIG._serialized_start=98
  _CONFIG._serialized_end=263
# @@protoc_insertion_point(module_scope)
